# Generated by Django 4.2.7 on 2023-12-06 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_rename_username_user_name_alter_user_is_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_member',
        ),
    ]
