# Generated by Django 4.2.7 on 2023-12-06 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_remove_user_is_member'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'permissions': [('add_members_to_org', 'view_members_in_org')]},
        ),
    ]
