# Generated by Django 4.2.7 on 2023-12-06 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['name'], 'permissions': [('add_members', 'Add members to an organisation'), ('view_members', 'View members of an organisation')]},
        ),
    ]
